### ISSUE TITLE
Dark mode issue when opening QC files (and maybe all of them)

### ISSUE THREAD

**Issue by GrubPL** [Mrfunreal/VDF-Lanugages-for-NotepadPlusPlus#1]
![image](https://github.com/Mrfunreal/VDF-Lanugages-for-NotepadPlusPlus/assets/141992850/da064c7f-dac9-4e56-8c87-452bdf544e8b)

i think this image should explain the issue well enough, works great in light mode... but its light mode

**Comment by Mrfunreal** [comment]
Problem being that all the highlight colors are set to contrast to bright mode only.
The green $modelname and the even darker blue commands would be barely legible on on the dark background.
Just look at that poor $bbox there.
But I can go through all languages and undo the background color if you wish.

**Comment by Mrfunreal** [comment]
I've updated all languages to allow text background color to be transparent.
Some colors will look very horrible on dark themes, which may require you to edit the XML files manually if you wanted to color issues on any theme that is really dark.
